language: python
python: '3.5'
before_install:
- export GH_TOKEN_FILE=$(mktemp); echo $GH_TOKEN > $GH_TOKEN_FILE; GH_TOKEN=""
install: true
before_script:
- "./scripts/tests.sh"
- git config --global user.email "akovalev@ptsecurity.com"
- git config --global user.name "Alexander Kovalev"
script:
- printenv
- TRAVIS_BRANCH="develop_ak" ./scripts/build-on-server.sh
before_deploy:
- ls -l build/
- GH_TOKEN="$(cat $GH_TOKEN_FILE)"
- git push --quiet "https://${GH_TOKEN}@github.com/devopshq/crosspm" --tags > /dev/null
deploy:
  provider: pypi
  user: alkov.pro
  password:
    secure: hPoe8xkHPfq5+fKgFqgoam16g2Asg7sIit8B9LCVfzLUGdPv3U3SBI1RuUMMZP3PWjW+55Y6H6V6FXfgcAqdmi+rVUPnvja67fkOp4ywgChBIc6HQwi01cCyFQ/tzK4NYsnRDpkyjdGcQ+L6Xp8fkeXbsDuXS2jQ38nqlgrWnqXBLOaZwkBAIhjdLPRuPko61aClQdO+VAtPkzlVfwYT1+dODQ91VH3jfOTa+nEPc4hcPp4QCkY8p0btMlzucB7XrFcf/rmMJT0oftKpH3bPYHkGH0B5oFLKIMcF21kNhbMtjagkf2REUvP9Za9++6PzFZQjgbeLV8OPP37PMSOls5QZUzYKe6MSFKBg8SF+2oswSEaKJkjiveanwt1/gDVusMNeACmFnzhzG05YfqEawACzsYzeo8FvmlSQ1ZMNmqh/v67sk/PKkYQjUqlggDP8tUCBHFxtwJeDmV6r7zyi/42lLHaQVa+C6EsXm2cKNJyxL3Zdrfv+IjUEZVIaq0UPw3w4vefzr5QzewYqlqjDWIsdII+KQSFDbFVN0YhSI33Vw5okuPEDzh4dZc79iqjLlz4qdQpPs6sPZzDcMha8oJt8HyaNtJjwN1lKEo9fBRfWp81KBFm59DQBlbF0mQ56dzuFh1v7pvb/eyDOjl91XacMo8FNCEFk0x2hIR7d4Pk=
  server: https://testpypi.python.org/pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
after_script:
- echo "yes we run after_script"
- echo "" > $GH_TOKEN_FILE
env:
  global:
    - secure: wiFL18iRrNU1t7ZBu571vWMvEdih8fX5wM1e0h0wyaa0OK2Rz2Ihsqnzv490vLvaXanRXrBMV8/QwskNwsJ0kOtaL43Xt4yaBqMkOVNprNAIFNofJrvlrAxzZ9m8TGzmSoHz3JkE0YHZSJRKYWzJW5+iI1r+rC2BRUGQG7tRmzef1tiOCoq76Ie2LD4+Pp5BkO2EdeC7O9+WRdOjizRwbBJ+1wc0mWc1Yb/5r76THNxAVDfdhW6k7AZGqaXIwSvVgmlfj3hjYKJGPP9bJOfaRpFMxBBA4cYXFLdEAaaC+8sc9E1TTvG+R3O5gGfz/RUJ5pIqBUVDMz4xAjysJHYY5W1RueEEaG9aDjtM5/oNVZGjbmQqhusi92nlEJoXmukv/YZUFARiw1cAFQFCSWMUUzoR1XfUpJewsKBCuJ8Akwf8GiK4c153tyYHAa371LDcBiEcylcLTF2M/0Vb+oIU1wX+x6rv1B7uEPZshmq5tVXYbUpezBYAFFIrZwgPxj1SITONgMdHFVCLfp+b1TIpE64A4FWrhWNJOXv5yzl8/xlyaN9hFBv1NebCBZFUEkzXvgIz/PxiEbI6jygKBdxaW9Iw9NUdByfFVAcczExRODsHP8TCWSzQTkdwDwKl2QUI0WsmeBraBovprWeye2lgfh8w6UVA5IK9Pj4kkXjOr8A=
